#!/usr/bin/env bash
#
# runpod_storage_setup.sh — Complete setup guide for RunPod S3 storage system
#
# This script walks through the setup process for the Scenario Reasoner LM
# storage system on RunPod, including credential configuration and testing.
#
# Usage:
#   bash runpod_storage_setup.sh
#

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

clear_screen() {
    printf "\033[2J\033[3J\033[1;1H"
}

print_header() {
    echo ""
    echo -e "${BLUE}========================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}========================================${NC}"
    echo ""
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

print_info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

# Check prerequisites
check_prerequisites() {
    print_header "Checking Prerequisites"
    
    local missing_deps=0
    
    # Check Python
    if ! command -v python &> /dev/null && ! command -v python3 &> /dev/null; then
        print_error "Python not found"
        missing_deps=$((missing_deps + 1))
    else
        print_success "Python found"
    fi
    
    # Check s3cmd
    if ! command -v s3cmd &> /dev/null; then
        print_warning "s3cmd not installed (required for download/upload)"
        echo "  Install: pip install s3cmd"
        missing_deps=$((missing_deps + 1))
    else
        print_success "s3cmd installed"
    fi
    
    # Check tmux
    if ! command -v tmux &> /dev/null; then
        print_warning "tmux not installed (required for daemon)"
        echo "  Install: apt-get install tmux (or brew install tmux on Mac)"
        missing_deps=$((missing_deps + 1))
    else
        print_success "tmux installed"
    fi
    
    # Check git (optional but recommended)
    if ! command -v git &> /dev/null; then
        print_warning "git not found (optional)"
    else
        print_success "git found"
    fi
    
    if [ ${missing_deps} -gt 0 ]; then
        print_error "Install missing dependencies before proceeding"
        return 1
    fi
    
    print_success "All prerequisites met"
    return 0
}

# Setup credentials
setup_credentials() {
    print_header "S3 Credentials Configuration"
    
    echo "This step will create a .env file with your S3 credentials."
    echo ""
    
    # Check if .env already exists
    if [ -f ".env" ]; then
        read -p "File .env already exists. Overwrite? (y/N) " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            print_info "Skipping credentials setup"
            return 0
        fi
    fi
    
    # Get S3 endpoint
    print_info "Enter S3 endpoint (default: https://s3.amazonaws.com)"
    read -p "  S3_ENDPOINT_URL: " S3_ENDPOINT_URL
    S3_ENDPOINT_URL="${S3_ENDPOINT_URL:-https://s3.amazonaws.com}"
    
    # Get access key
    print_info "Enter S3 access key ID"
    read -p "  S3_ACCESS_KEY_ID: " S3_ACCESS_KEY_ID
    if [ -z "$S3_ACCESS_KEY_ID" ]; then
        print_error "Access key is required"
        return 1
    fi
    
    # Get secret key
    print_info "Enter S3 secret access key"
    read -sp "  S3_SECRET_ACCESS_KEY: " S3_SECRET_ACCESS_KEY
    echo
    if [ -z "$S3_SECRET_ACCESS_KEY" ]; then
        print_error "Secret key is required"
        return 1
    fi
    
    # Get bucket name
    print_info "Enter S3 bucket name"
    read -p "  S3_BUCKET: " S3_BUCKET
    if [ -z "$S3_BUCKET" ]; then
        print_error "Bucket name is required"
        return 1
    fi
    
    # Write .env file
    cat > .env << EOF
# Generated by runpod_storage_setup.sh
export S3_ENDPOINT_URL="${S3_ENDPOINT_URL}"
export S3_ACCESS_KEY_ID="${S3_ACCESS_KEY_ID}"
export S3_SECRET_ACCESS_KEY="${S3_SECRET_ACCESS_KEY}"
export S3_BUCKET="${S3_BUCKET}"
export S3_DOWNLOAD_PREFIX="datasets/scenario-v1"
export S3_UPLOAD_PREFIX="scenario-reasoner-lm"
export UPLOAD_INTERVAL="600"
EOF
    
    chmod 600 .env
    print_success "Credentials saved to .env"
    print_warning "IMPORTANT: Add .env to .gitignore to prevent accidental commits"
    
    return 0
}

# Test S3 connection
test_s3_connection() {
    print_header "Testing S3 Connection"
    
    if [ ! -f ".env" ]; then
        print_error ".env file not found"
        print_info "Run credentials setup first"
        return 1
    fi
    
    source .env
    
    if ! command -v s3cmd &> /dev/null; then
        print_warning "s3cmd not installed, skipping connection test"
        return 0
    fi
    
    # Create temporary s3cmd config
    S3CMD_CONFIG=$(mktemp /tmp/s3cmd_test.XXXXXX)
    trap "rm -f '${S3CMD_CONFIG}'" RETURN
    
    cat > "${S3CMD_CONFIG}" << EOF
[default]
access_key = ${S3_ACCESS_KEY_ID}
secret_key = ${S3_SECRET_ACCESS_KEY}
host_base = $(echo ${S3_ENDPOINT_URL} | sed 's|https://||g;s|http://||g')
host_bucket = %(bucket)s.$(echo ${S3_ENDPOINT_URL} | sed 's|https://||g;s|http://||g')
use_https = true
signature_version = s3v4
EOF
    
    print_info "Testing S3 connection..."
    
    if s3cmd --config="${S3CMD_CONFIG}" ls "s3://${S3_BUCKET}" &>/dev/null; then
        print_success "S3 connection successful"
        print_success "Bucket: ${S3_BUCKET}"
        return 0
    else
        print_error "S3 connection failed"
        print_info "Check your credentials and bucket permissions"
        return 1
    fi
}

# Test storage scripts
test_storage_scripts() {
    print_header "Testing Storage Scripts"
    
    # Check if scripts exist
    if [ ! -f "storage/s3_download.sh" ]; then
        print_error "storage/s3_download.sh not found"
        return 1
    fi
    
    if [ ! -f "storage/s3_upload.sh" ]; then
        print_error "storage/s3_upload.sh not found"
        return 1
    fi
    
    if [ ! -f "storage/s3_upload_daemon.sh" ]; then
        print_error "storage/s3_upload_daemon.sh not found"
        return 1
    fi
    
    print_success "All storage scripts found"
    
    # Make scripts executable
    chmod +x storage/s3_*.sh
    chmod +x storage/orchestrate_storage.sh
    
    print_success "Scripts made executable"
    
    # Test dry-run download
    source .env
    
    print_info "Testing download (dry-run)..."
    print_info "Note: This will create test directories but not download large files"
    
    return 0
}

# Show configuration summary
show_summary() {
    print_header "Configuration Summary"
    
    if [ ! -f ".env" ]; then
        print_error ".env file not found"
        return 1
    fi
    
    source .env
    
    echo "S3 Configuration:"
    echo "  Endpoint:        ${S3_ENDPOINT_URL}"
    echo "  Bucket:          ${S3_BUCKET}"
    echo "  Download path:   ${S3_DOWNLOAD_PREFIX}"
    echo "  Upload path:     ${S3_UPLOAD_PREFIX}"
    echo ""
    echo "Storage Paths:"
    echo "  Project root:    $(pwd)"
    echo "  Data dir:        ./data"
    echo "  Experiments:     ./experiments"
    echo "  Artifacts:       ./artifacts"
    echo ""
    echo "Daemon Configuration:"
    echo "  Upload interval: ${UPLOAD_INTERVAL}s"
    echo ""
}

# Show next steps
show_next_steps() {
    print_header "Next Steps"
    
    echo "Your S3 storage system is configured! Here's what to do next:"
    echo ""
    echo "1. Download training data:"
    echo "   bash storage/orchestrate_storage.sh download"
    echo ""
    echo "2. Start the upload daemon:"
    echo "   bash storage/s3_upload_daemon.sh start"
    echo ""
    echo "3. Run training (daemon uploads results in background):"
    echo "   python runpod/train.py"
    echo ""
    echo "4. Monitor uploads:"
    echo "   bash storage/s3_upload_daemon.sh logs"
    echo ""
    echo "5. Or use the full pipeline:"
    echo "   bash storage/orchestrate_storage.sh pipeline"
    echo ""
    echo "For more information, see:"
    echo "  - storage/README.md (complete documentation)"
    echo "  - storage/.env.example (configuration reference)"
    echo ""
}

# Main
main() {
    clear_screen
    
    print_header "Scenario Reasoner LM — RunPod Storage Setup"
    
    echo "This script will help you configure S3 storage for training on RunPod."
    echo ""
    
    # Run setup steps
    if ! check_prerequisites; then
        print_error "Please install missing dependencies and try again"
        exit 1
    fi
    
    echo ""
    read -p "Continue with credentials setup? (y/N) " -n 1 -r
    echo
    
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        print_info "Setup cancelled"
        exit 0
    fi
    
    if ! setup_credentials; then
        exit 1
    fi
    
    echo ""
    read -p "Test S3 connection? (y/N) " -n 1 -r
    echo
    
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        test_s3_connection || print_warning "Connection test failed (check credentials)"
    fi
    
    echo ""
    if ! test_storage_scripts; then
        print_error "Storage scripts not found or not executable"
        exit 1
    fi
    
    show_summary
    show_next_steps
    
    print_success "Setup complete!"
}

main
